# Generated by Django 5.0.4 on 2024-04-04 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('studio', models.CharField(choices=[('EA', 'Electronic Arts'), ('SE', 'Square Enix'), ('ND', 'Naughty Dog'), ('NIN', 'Nintendo'), ('LS', 'Larian Studios'), ('PS', 'PlayStation'), ('BGS', 'Bethseda Game Studios'), ('CAP', 'Capcom'), ('CD', 'Crystal Dynamics'), ('EG', 'Epic Games'), ('GG', 'Guerrilla Games'), ('RIO', 'Riot Games'), ('RG', 'Rockstar Games'), ('SE', 'SEGA'), ('V', 'Valve')], default='EA', max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.game')),
            ],
        ),
    ]
