# Generated by Django 5.0.4 on 2024-04-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_developer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='developer',
            name='date',
            field=models.DateField(verbose_name='Relase Date'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='studio',
            field=models.CharField(choices=[('EA', 'Electronic Arts'), ('SQ', 'Square Enix'), ('ND', 'Naughty Dog'), ('NIN', 'Nintendo'), ('LS', 'Larian Studios'), ('PS', 'PlayStation'), ('BGS', 'Bethseda Game Studios'), ('CAP', 'Capcom'), ('CD', 'Crystal Dynamics'), ('EG', 'Epic Games'), ('GG', 'Guerrilla Games'), ('RIO', 'Riot Games'), ('RG', 'Rockstar Games'), ('SE', 'SEGA'), ('V', 'Valve')], default='EA', max_length=100),
        ),
    ]
